# Generated by Django 3.0.4 on 2020-03-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogIn_Page',
        ),
    ]
