# Generated by Django 3.0.3 on 2020-03-27 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200326_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
