# Generated by Django 3.0.3 on 2020-03-27 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0009_auto_20200327_1434'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userProfile',
        ),
    ]
