# Generated by Django 3.0.3 on 2020-03-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200329_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='reimbursementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('sid', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('year', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('mobile_number', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
            ],
        ),
    ]
