# Generated by Django 3.0.4 on 2020-04-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auditorium_lecturehall_lab_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='auditorium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_club_or_technical_society_or_NSS_or_NCC', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('event_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('time', models.TimeField(blank=True, default=None, null=True)),
                ('brief_event_description', models.TextField(blank=True, default=None, null=True)),
                ('secretary_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('secretary_SID', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=None, max_length=50, null=True)),
                ('sid', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('year', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('mobile_number', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('place', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('date_from', models.DateField(blank=True, default=None, null=True)),
                ('date_to', models.DateField(blank=True, default=None, null=True)),
                ('time_from', models.TimeField(blank=True, default=None, null=True)),
                ('time_to', models.TimeField(blank=True, default=None, null=True)),
                ('brief_project_description', models.TextField(blank=True, default=None, null=True)),
                ('project_report', models.FileField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='lecturehalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_club_or_technical_society', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('date_from', models.DateField(blank=True, default=None, null=True)),
                ('date_to', models.DateField(blank=True, default=None, null=True)),
                ('time_from', models.TimeField(blank=True, default=None, null=True)),
                ('time_to', models.TimeField(blank=True, default=None, null=True)),
                ('place', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('reason', models.TextField(blank=True, default=None, null=True)),
                ('secretary_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('secretary_SID', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='auditorium_lectureHall_lab',
        ),
        migrations.RemoveField(
            model_name='event',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='event',
            name='email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='event',
            name='year',
        ),
        migrations.AddField(
            model_name='event',
            name='IFSC_code',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='PAN_card_number',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='account_holder_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='account_number',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='advance_amount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='advance_required',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='advance_required_justification',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='brief_event_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_of_event_from',
            field=models.DateField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_of_event_to',
            field=models.DateField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='expected_expenditure_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name_of_club_or_technical_society',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='secretary_SID',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='secretary_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time_of_event_from',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time_of_event_to',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='total_expected_expenditure',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venues',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='IFSC_code',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='PAN_card_number',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='accomodation_or_food',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='account_holder_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='account_number',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='attach_bills',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='attach_proofs',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='brief_event_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='date_of_event_from',
            field=models.DateField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='date_of_event_to',
            field=models.DateField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='dates_for_which_team_will_be_away_from',
            field=models.DateField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='dates_for_which_team_will_be_away_to',
            field=models.DateField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='event_name',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='institute',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='mode_of_travel',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='name_of_club_or_technical_society',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='total_expenditure',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='full_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/profile_pic'),
        ),
    ]
