# Generated by Django 3.0.4 on 2020-04-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20200406_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_approve_LH_form', 'approve_LH_form'),)},
        ),
    ]
