# Generated by Django 3.0.3 on 2020-04-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20200416_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorium',
            name='filed_by',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='filed_by',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='labs',
            name='filed_by',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='lecturehalls',
            name='filed_by',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='filed_by',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='statue.jpg', null=True, upload_to=''),
        ),
    ]
