# Generated by Django 3.0.3 on 2020-04-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20200418_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='society_or_club_name',
            field=models.CharField(blank=True, choices=[('AMS', 'AMS'), ('ASCE', 'ASCE'), ('ASME', 'ASME'), ('ACM', 'ACM'), ('IIM', 'IIM'), ('ISTE', 'ISTE'), ('IEEE', 'IEEE'), ('IETE', 'IETE'), ('SAE', 'SAE'), ('SME', 'SME'), ('SESI', 'SESI'), ('ROBOTICS', 'ROBOTICS'), ('NSS', 'NSS'), ('NCC', 'NCC'), ('Art and Photography Club', 'Art and Photography Club'), ('Music Club', 'Music Club'), ('Dramatics Club', 'Dramatics Club'), ('Speakers Association & Study Circle', 'Speakers Association & Study Circle'), ('Projection Design Club', 'Projection Design Club'), ('Rotaract Club', 'Rotaract Club'), ('Communication Club', 'Communication Club'), ('Student Counselling Cell', 'Student Counselling Cell'), ('Women Empowerment Cell', 'Women Empowerment Cell'), ('EIC', 'EIC')], default=None, max_length=50, null=True),
        ),
    ]
