# Generated by Django 3.0.3 on 2020-04-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20200418_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='statue.jpg', null=True, upload_to='profile_pic/'),
        ),
    ]
