# Generated by Django 3.0.3 on 2020-04-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20200418_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labs',
            name='project_report',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='attach_bills',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='attach_proofs',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files/'),
        ),
    ]
