# Generated by Django 3.0.3 on 2020-04-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20200418_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/statue.jpg', null=True, upload_to='profile_pic/'),
        ),
    ]
