# Generated by Django 3.0.4 on 2020-04-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20200418_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturehalls',
            name='reason_for_disapproval',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='CDGC_approval',
            field=models.CharField(choices=[('None', '------'), ('approved', 'approved'), ('not approved', 'not approved')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='DA_approval',
            field=models.CharField(choices=[('None', '------'), ('approved', 'approved'), ('not approved', 'not approved')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='DSA_approval',
            field=models.CharField(choices=[('None', '------'), ('approved', 'approved'), ('not approved', 'not approved')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='OI_approval',
            field=models.CharField(choices=[('None', '------'), ('approved', 'approved'), ('not approved', 'not approved')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='name_of_club_or_technical_society',
            field=models.CharField(blank=True, choices=[('None', '------'), ('AMS', 'AMS'), ('ASCE', 'ASCE'), ('ASME', 'ASME'), ('ACM', 'ACM'), ('IIM', 'IIM'), ('ISTE', 'ISTE'), ('IEEE', 'IEEE'), ('IETE', 'IETE'), ('SAE', 'SAE'), ('SME', 'SME'), ('SESI', 'SESI'), ('ROBOTICS', 'ROBOTICS'), ('NSS', 'NSS'), ('NCC', 'NCC'), ('Art and Photography Club', 'Art and Photography Club'), ('Music Club', 'Music Club'), ('Dramatics Club', 'Dramatics Club'), ('Speakers Association & Study Circle', 'Speakers Association & Study Circle'), ('Projection Design Club', 'Projection Design Club'), ('Rotaract Club', 'Rotaract Club'), ('Communication Club', 'Communication Club'), ('Student Counselling Cell', 'Student Counselling Cell'), ('Women Empowerment Cell', 'Women Empowerment Cell'), ('EIC', 'EIC')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='type',
            field=models.CharField(blank=True, choices=[('None', '------'), ('Technical', 'Technical'), ('Cultural', 'Cultural')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='CA_approval',
            field=models.CharField(choices=[('None', '------'), ('approved', 'approved'), ('not approved', 'not approved')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='CCS_CTS_approval',
            field=models.CharField(choices=[('None', '------'), ('approved', 'approved'), ('not approved', 'not approved')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='DA_approval',
            field=models.CharField(choices=[('None', '------'), ('approved', 'approved'), ('not approved', 'not approved')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='DSA_approval',
            field=models.CharField(choices=[('None', '------'), ('approved', 'approved'), ('not approved', 'not approved')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='OI_approval',
            field=models.CharField(choices=[('None', '------'), ('approved', 'approved'), ('not approved', 'not approved')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_of_club_or_technical_society',
            field=models.CharField(blank=True, choices=[('None', '------'), ('AMS', 'AMS'), ('ASCE', 'ASCE'), ('ASME', 'ASME'), ('ACM', 'ACM'), ('IIM', 'IIM'), ('ISTE', 'ISTE'), ('IEEE', 'IEEE'), ('IETE', 'IETE'), ('SAE', 'SAE'), ('SME', 'SME'), ('SESI', 'SESI'), ('ROBOTICS', 'ROBOTICS'), ('NSS', 'NSS'), ('NCC', 'NCC'), ('Art and Photography Club', 'Art and Photography Club'), ('Music Club', 'Music Club'), ('Dramatics Club', 'Dramatics Club'), ('Speakers Association & Study Circle', 'Speakers Association & Study Circle'), ('Projection Design Club', 'Projection Design Club'), ('Rotaract Club', 'Rotaract Club'), ('Communication Club', 'Communication Club'), ('Student Counselling Cell', 'Student Counselling Cell'), ('Women Empowerment Cell', 'Women Empowerment Cell'), ('EIC', 'EIC')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('None', '------'), ('Technical', 'Technical'), ('Cultural', 'Cultural')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='DA_approval',
            field=models.CharField(choices=[('None', '------'), ('approved', 'approved'), ('not approved', 'not approved')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='DSA_approval',
            field=models.CharField(choices=[('None', '------'), ('approved', 'approved'), ('not approved', 'not approved')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='HOD_approval',
            field=models.CharField(choices=[('None', '------'), ('approved', 'approved'), ('not approved', 'not approved')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='branch',
            field=models.CharField(blank=True, choices=[('None', '------'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Production and Industrial Engineering', 'Production and Industrial Engineering'), ('Aerospace Engineering', 'Aerospace Engineering'), ('Metallurgical Engineering', 'Metallurgical Engineering')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='department_related_to_project',
            field=models.CharField(blank=True, choices=[('None', '------'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Production and Industrial Engineering', 'Production and Industrial Engineering'), ('Aerospace Engineering', 'Aerospace Engineering'), ('Metallurgical Engineering', 'Metallurgical Engineering')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='OISecurity_approval',
            field=models.CharField(choices=[('None', '------'), ('approved', 'approved'), ('not approved', 'not approved')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='OI_approval',
            field=models.CharField(choices=[('None', '------'), ('approved', 'approved'), ('not approved', 'not approved')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='name_of_club_or_technical_society',
            field=models.CharField(blank=True, choices=[('None', '------'), ('AMS', 'AMS'), ('ASCE', 'ASCE'), ('ASME', 'ASME'), ('ACM', 'ACM'), ('IIM', 'IIM'), ('ISTE', 'ISTE'), ('IEEE', 'IEEE'), ('IETE', 'IETE'), ('SAE', 'SAE'), ('SME', 'SME'), ('SESI', 'SESI'), ('ROBOTICS', 'ROBOTICS'), ('NSS', 'NSS'), ('NCC', 'NCC'), ('Art and Photography Club', 'Art and Photography Club'), ('Music Club', 'Music Club'), ('Dramatics Club', 'Dramatics Club'), ('Speakers Association & Study Circle', 'Speakers Association & Study Circle'), ('Projection Design Club', 'Projection Design Club'), ('Rotaract Club', 'Rotaract Club'), ('Communication Club', 'Communication Club'), ('Student Counselling Cell', 'Student Counselling Cell'), ('Women Empowerment Cell', 'Women Empowerment Cell'), ('EIC', 'EIC')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='type',
            field=models.CharField(blank=True, choices=[('None', '------'), ('Technical', 'Technical'), ('Cultural', 'Cultural')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='CA_approval',
            field=models.CharField(choices=[('None', '------'), ('approved', 'approved'), ('not approved', 'not approved')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='CCS_CTS_approval',
            field=models.CharField(choices=[('None', '------'), ('approved', 'approved'), ('not approved', 'not approved')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='DA_approval',
            field=models.CharField(choices=[('None', '------'), ('approved', 'approved'), ('not approved', 'not approved')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='DSA_approval',
            field=models.CharField(choices=[('None', '------'), ('approved', 'approved'), ('not approved', 'not approved')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='OI_approval',
            field=models.CharField(choices=[('None', '------'), ('approved', 'approved'), ('not approved', 'not approved')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='Secretary_approval',
            field=models.CharField(choices=[('None', '------'), ('approved', 'approved'), ('not approved', 'not approved')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='branch',
            field=models.CharField(blank=True, choices=[('None', '------'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Production and Industrial Engineering', 'Production and Industrial Engineering'), ('Aerospace Engineering', 'Aerospace Engineering'), ('Metallurgical Engineering', 'Metallurgical Engineering')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='name_of_club_or_technical_society',
            field=models.CharField(blank=True, choices=[('None', '------'), ('AMS', 'AMS'), ('ASCE', 'ASCE'), ('ASME', 'ASME'), ('ACM', 'ACM'), ('IIM', 'IIM'), ('ISTE', 'ISTE'), ('IEEE', 'IEEE'), ('IETE', 'IETE'), ('SAE', 'SAE'), ('SME', 'SME'), ('SESI', 'SESI'), ('ROBOTICS', 'ROBOTICS'), ('NSS', 'NSS'), ('NCC', 'NCC'), ('Art and Photography Club', 'Art and Photography Club'), ('Music Club', 'Music Club'), ('Dramatics Club', 'Dramatics Club'), ('Speakers Association & Study Circle', 'Speakers Association & Study Circle'), ('Projection Design Club', 'Projection Design Club'), ('Rotaract Club', 'Rotaract Club'), ('Communication Club', 'Communication Club'), ('Student Counselling Cell', 'Student Counselling Cell'), ('Women Empowerment Cell', 'Women Empowerment Cell'), ('EIC', 'EIC')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='type',
            field=models.CharField(blank=True, choices=[('None', '------'), ('Technical', 'Technical'), ('Cultural', 'Cultural')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(blank=True, choices=[('None', '------'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Production and Industrial Engineering', 'Production and Industrial Engineering'), ('Aerospace Engineering', 'Aerospace Engineering'), ('Metallurgical Engineering', 'Metallurgical Engineering')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('None', '------'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Production and Industrial Engineering', 'Production and Industrial Engineering'), ('Aerospace Engineering', 'Aerospace Engineering'), ('Metallurgical Engineering', 'Metallurgical Engineering')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='society_or_club_name',
            field=models.CharField(blank=True, choices=[('None', '------'), ('AMS', 'AMS'), ('ASCE', 'ASCE'), ('ASME', 'ASME'), ('ACM', 'ACM'), ('IIM', 'IIM'), ('ISTE', 'ISTE'), ('IEEE', 'IEEE'), ('IETE', 'IETE'), ('SAE', 'SAE'), ('SME', 'SME'), ('SESI', 'SESI'), ('ROBOTICS', 'ROBOTICS'), ('NSS', 'NSS'), ('NCC', 'NCC'), ('Art and Photography Club', 'Art and Photography Club'), ('Music Club', 'Music Club'), ('Dramatics Club', 'Dramatics Club'), ('Speakers Association & Study Circle', 'Speakers Association & Study Circle'), ('Projection Design Club', 'Projection Design Club'), ('Rotaract Club', 'Rotaract Club'), ('Communication Club', 'Communication Club'), ('Student Counselling Cell', 'Student Counselling Cell'), ('Women Empowerment Cell', 'Women Empowerment Cell'), ('EIC', 'EIC')], default=None, max_length=50, null=True),
        ),
    ]
