# Generated by Django 3.0.3 on 2020-04-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_auto_20200419_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorium',
            name='progress',
            field=models.CharField(choices=[('in-progress', 'in-progress'), ('approved', 'approved'), ('dismissed', 'dismissed')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='labs',
            name='progress',
            field=models.CharField(choices=[('in-progress', 'in-progress'), ('approved', 'approved'), ('dismissed', 'dismissed')], default='in-progress', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lecturehalls',
            name='progress',
            field=models.CharField(choices=[('in-progress', 'in-progress'), ('approved', 'approved'), ('dismissed', 'dismissed')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='place',
            field=models.CharField(blank=True, choices=[('LAB-1', 'LAB-1'), ('LAB-2', 'LAB-2'), ('LAB-3', 'LAB-3')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='place',
            field=models.CharField(blank=True, choices=[('L-1', 'L-1'), ('L-2', 'L-2'), ('L-3', 'L-3'), ('L-4', 'L-4'), ('L-5', 'L-5'), ('L-6', 'L-6'), ('L-7', 'L-7'), ('L-8', 'L-8'), ('L-9', 'L-9'), ('L-10', 'L-10'), ('L-11', 'L-11'), ('L-12', 'L-12'), ('L-13', 'L-13'), ('L-14', 'L-14'), ('L-15', 'L-15'), ('L-16', 'L-16'), ('L-17', 'L-17'), ('L-18', 'L-18'), ('L-19', 'L-19'), ('L-20', 'L-20'), ('L-21', 'L-21'), ('L-22', 'L-22'), ('L-23', 'L-23'), ('L-24', 'L-24'), ('L-25', 'L-25'), ('L-26', 'L-26'), ('L-27', 'L-27'), ('L-28', 'L-28'), ('L-29', 'L-29'), ('L-30', 'L-30'), ('L-31', 'L-31')], default=None, max_length=100, null=True),
        ),
    ]
