# Generated by Django 3.0.4 on 2020-04-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20200420_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditorium',
            old_name='time',
            new_name='time_from',
        ),
        migrations.AddField(
            model_name='auditorium',
            name='time_to',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
