# Generated by Django 3.0.4 on 2020-04-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20200420_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorium',
            name='brief_event_description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='event_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='name_of_club_or_technical_society',
            field=models.CharField(choices=[('None', '------'), ('AMS', 'AMS'), ('ASCE', 'ASCE'), ('ASME', 'ASME'), ('ACM', 'ACM'), ('IIM', 'IIM'), ('ISTE', 'ISTE'), ('IEEE', 'IEEE'), ('IETE', 'IETE'), ('SAE', 'SAE'), ('SME', 'SME'), ('SESI', 'SESI'), ('ROBOTICS', 'ROBOTICS'), ('NSS', 'NSS'), ('NCC', 'NCC'), ('Art and Photography Club', 'Art and Photography Club'), ('Music Club', 'Music Club'), ('Dramatics Club', 'Dramatics Club'), ('Speakers Association & Study Circle', 'Speakers Association & Study Circle'), ('Projection Design Club', 'Projection Design Club'), ('Rotaract Club', 'Rotaract Club'), ('Communication Club', 'Communication Club'), ('Student Counselling Cell', 'Student Counselling Cell'), ('Women Empowerment Cell', 'Women Empowerment Cell'), ('EIC', 'EIC')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='reason_for_disapproval',
            field=models.TextField(default=None, help_text='Only required, if you are going to disapprove the application', null=True),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='secretary_SID',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='secretary_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='time_from',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='time_to',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='type',
            field=models.CharField(choices=[('None', '------'), ('Technical', 'Technical'), ('Cultural', 'Cultural')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='advance_amount',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='advance_required_justification',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='brief_event_description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_of_event_from',
            field=models.DateField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_of_event_to',
            field=models.DateField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='expected_expenditure_description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_of_club_or_technical_society',
            field=models.CharField(choices=[('None', '------'), ('AMS', 'AMS'), ('ASCE', 'ASCE'), ('ASME', 'ASME'), ('ACM', 'ACM'), ('IIM', 'IIM'), ('ISTE', 'ISTE'), ('IEEE', 'IEEE'), ('IETE', 'IETE'), ('SAE', 'SAE'), ('SME', 'SME'), ('SESI', 'SESI'), ('ROBOTICS', 'ROBOTICS'), ('NSS', 'NSS'), ('NCC', 'NCC'), ('Art and Photography Club', 'Art and Photography Club'), ('Music Club', 'Music Club'), ('Dramatics Club', 'Dramatics Club'), ('Speakers Association & Study Circle', 'Speakers Association & Study Circle'), ('Projection Design Club', 'Projection Design Club'), ('Rotaract Club', 'Rotaract Club'), ('Communication Club', 'Communication Club'), ('Student Counselling Cell', 'Student Counselling Cell'), ('Women Empowerment Cell', 'Women Empowerment Cell'), ('EIC', 'EIC')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='reason_for_disapproval',
            field=models.TextField(default=None, help_text='Only required, if you are going to disapprove the application', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='secretary_SID',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='secretary_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_of_event_from',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_of_event_to',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_expected_expenditure',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('None', '------'), ('Technical', 'Technical'), ('Cultural', 'Cultural')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venues',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='branch',
            field=models.CharField(choices=[('None', '------'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Production and Industrial Engineering', 'Production and Industrial Engineering'), ('Aerospace Engineering', 'Aerospace Engineering'), ('Metallurgical Engineering', 'Metallurgical Engineering')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='brief_project_description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='date_from',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='date_to',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='department_related_to_project',
            field=models.CharField(choices=[('None', '------'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Production and Industrial Engineering', 'Production and Industrial Engineering'), ('Aerospace Engineering', 'Aerospace Engineering'), ('Metallurgical Engineering', 'Metallurgical Engineering')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='full_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='mobile_number',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='place',
            field=models.CharField(choices=[('LAB-1', 'LAB-1'), ('LAB-2', 'LAB-2'), ('LAB-3', 'LAB-3')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='project_report',
            field=models.FileField(default=None, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='labs',
            name='reason_for_disapproval',
            field=models.TextField(default=None, help_text='Only required, if you are going to disapprove the application', null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='sid',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='time_from',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='time_to',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='date_from',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='date_to',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='name_of_club_or_technical_society',
            field=models.CharField(choices=[('None', '------'), ('AMS', 'AMS'), ('ASCE', 'ASCE'), ('ASME', 'ASME'), ('ACM', 'ACM'), ('IIM', 'IIM'), ('ISTE', 'ISTE'), ('IEEE', 'IEEE'), ('IETE', 'IETE'), ('SAE', 'SAE'), ('SME', 'SME'), ('SESI', 'SESI'), ('ROBOTICS', 'ROBOTICS'), ('NSS', 'NSS'), ('NCC', 'NCC'), ('Art and Photography Club', 'Art and Photography Club'), ('Music Club', 'Music Club'), ('Dramatics Club', 'Dramatics Club'), ('Speakers Association & Study Circle', 'Speakers Association & Study Circle'), ('Projection Design Club', 'Projection Design Club'), ('Rotaract Club', 'Rotaract Club'), ('Communication Club', 'Communication Club'), ('Student Counselling Cell', 'Student Counselling Cell'), ('Women Empowerment Cell', 'Women Empowerment Cell'), ('EIC', 'EIC')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='place',
            field=models.CharField(choices=[('L-1', 'L-1'), ('L-2', 'L-2'), ('L-3', 'L-3'), ('L-4', 'L-4'), ('L-5', 'L-5'), ('L-6', 'L-6'), ('L-7', 'L-7'), ('L-8', 'L-8'), ('L-9', 'L-9'), ('L-10', 'L-10'), ('L-11', 'L-11'), ('L-12', 'L-12'), ('L-13', 'L-13'), ('L-14', 'L-14'), ('L-15', 'L-15'), ('L-16', 'L-16'), ('L-17', 'L-17'), ('L-18', 'L-18'), ('L-19', 'L-19'), ('L-20', 'L-20'), ('L-21', 'L-21'), ('L-22', 'L-22'), ('L-23', 'L-23'), ('L-24', 'L-24'), ('L-25', 'L-25'), ('L-26', 'L-26'), ('L-27', 'L-27'), ('L-28', 'L-28'), ('L-29', 'L-29'), ('L-30', 'L-30'), ('L-31', 'L-31')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='reason',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='reason_for_disapproval',
            field=models.TextField(default=None, help_text='Only required, if you are going to disapprove the application', null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='secretary_SID',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='secretary_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='time_from',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='time_to',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='type',
            field=models.CharField(choices=[('None', '------'), ('Technical', 'Technical'), ('Cultural', 'Cultural')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='accomodation_or_food',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='attach_bills',
            field=models.FileField(default=None, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='attach_proofs',
            field=models.FileField(default=None, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='branch',
            field=models.CharField(choices=[('None', '------'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Production and Industrial Engineering', 'Production and Industrial Engineering'), ('Aerospace Engineering', 'Aerospace Engineering'), ('Metallurgical Engineering', 'Metallurgical Engineering')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='brief_event_description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='date_of_event_from',
            field=models.DateField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='date_of_event_to',
            field=models.DateField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='dates_for_which_team_will_be_away_from',
            field=models.DateField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='dates_for_which_team_will_be_away_to',
            field=models.DateField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='event_name',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='institute',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='mobile_number',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='mode_of_travel',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='name_of_club_or_technical_society',
            field=models.CharField(choices=[('None', '------'), ('AMS', 'AMS'), ('ASCE', 'ASCE'), ('ASME', 'ASME'), ('ACM', 'ACM'), ('IIM', 'IIM'), ('ISTE', 'ISTE'), ('IEEE', 'IEEE'), ('IETE', 'IETE'), ('SAE', 'SAE'), ('SME', 'SME'), ('SESI', 'SESI'), ('ROBOTICS', 'ROBOTICS'), ('NSS', 'NSS'), ('NCC', 'NCC'), ('Art and Photography Club', 'Art and Photography Club'), ('Music Club', 'Music Club'), ('Dramatics Club', 'Dramatics Club'), ('Speakers Association & Study Circle', 'Speakers Association & Study Circle'), ('Projection Design Club', 'Projection Design Club'), ('Rotaract Club', 'Rotaract Club'), ('Communication Club', 'Communication Club'), ('Student Counselling Cell', 'Student Counselling Cell'), ('Women Empowerment Cell', 'Women Empowerment Cell'), ('EIC', 'EIC')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='reason_for_disapproval',
            field=models.TextField(default=None, help_text='Only required, if you are going to disapprove the application', null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='sid',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='total_expenditure',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='type',
            field=models.CharField(choices=[('None', '------'), ('Technical', 'Technical'), ('Cultural', 'Cultural')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='DOB',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(choices=[('None', '------'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Production and Industrial Engineering', 'Production and Industrial Engineering'), ('Aerospace Engineering', 'Aerospace Engineering'), ('Metallurgical Engineering', 'Metallurgical Engineering')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('None', '------'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Production and Industrial Engineering', 'Production and Industrial Engineering'), ('Aerospace Engineering', 'Aerospace Engineering'), ('Metallurgical Engineering', 'Metallurgical Engineering')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/statue.jpg', null=True, upload_to='profile_pic/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sid',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='society_or_club_name',
            field=models.CharField(choices=[('None', '------'), ('AMS', 'AMS'), ('ASCE', 'ASCE'), ('ASME', 'ASME'), ('ACM', 'ACM'), ('IIM', 'IIM'), ('ISTE', 'ISTE'), ('IEEE', 'IEEE'), ('IETE', 'IETE'), ('SAE', 'SAE'), ('SME', 'SME'), ('SESI', 'SESI'), ('ROBOTICS', 'ROBOTICS'), ('NSS', 'NSS'), ('NCC', 'NCC'), ('Art and Photography Club', 'Art and Photography Club'), ('Music Club', 'Music Club'), ('Dramatics Club', 'Dramatics Club'), ('Speakers Association & Study Circle', 'Speakers Association & Study Circle'), ('Projection Design Club', 'Projection Design Club'), ('Rotaract Club', 'Rotaract Club'), ('Communication Club', 'Communication Club'), ('Student Counselling Cell', 'Student Counselling Cell'), ('Women Empowerment Cell', 'Women Empowerment Cell'), ('EIC', 'EIC')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='date_from',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='date_to',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='is_booked',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='time_from',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='time_to',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_name',
            field=models.CharField(choices=[('L-1', 'L-1'), ('L-2', 'L-2'), ('L-3', 'L-3'), ('L-4', 'L-4'), ('L-5', 'L-5'), ('L-6', 'L-6'), ('L-7', 'L-7'), ('L-8', 'L-8'), ('L-9', 'L-9'), ('L-10', 'L-10'), ('L-11', 'L-11'), ('L-12', 'L-12'), ('L-13', 'L-13'), ('L-14', 'L-14'), ('L-15', 'L-15'), ('L-16', 'L-16'), ('L-17', 'L-17'), ('L-18', 'L-18'), ('L-19', 'L-19'), ('L-20', 'L-20'), ('L-21', 'L-21'), ('L-22', 'L-22'), ('L-23', 'L-23'), ('L-24', 'L-24'), ('L-25', 'L-25'), ('L-26', 'L-26'), ('L-27', 'L-27'), ('L-28', 'L-28'), ('L-29', 'L-29'), ('L-30', 'L-30'), ('L-31', 'L-31'), ('LAB-1', 'LAB-1'), ('LAB-2', 'LAB-2'), ('LAB-3', 'LAB-3'), ('Auditorium', 'Auditorium')], default=None, max_length=50, null=True),
        ),
    ]
