# Generated by Django 3.0.4 on 2020-04-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_auto_20200420_2108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='venue',
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='progress',
            field=models.CharField(choices=[('None', '------'), ('in-progress', 'in-progress'), ('approved', 'approved'), ('dismissed', 'dismissed')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='place',
            field=models.CharField(choices=[('None', '------'), ('LAB-1', 'LAB-1'), ('LAB-2', 'LAB-2'), ('LAB-3', 'LAB-3')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='progress',
            field=models.CharField(choices=[('None', '------'), ('in-progress', 'in-progress'), ('approved', 'approved'), ('dismissed', 'dismissed')], default='in-progress', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='year',
            field=models.CharField(choices=[('N', '------'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='place',
            field=models.CharField(choices=[('None', '------'), ('L-1', 'L-1'), ('L-2', 'L-2'), ('L-3', 'L-3'), ('L-4', 'L-4'), ('L-5', 'L-5'), ('L-6', 'L-6'), ('L-7', 'L-7'), ('L-8', 'L-8'), ('L-9', 'L-9'), ('L-10', 'L-10'), ('L-11', 'L-11'), ('L-12', 'L-12'), ('L-13', 'L-13'), ('L-14', 'L-14'), ('L-15', 'L-15'), ('L-16', 'L-16'), ('L-17', 'L-17'), ('L-18', 'L-18'), ('L-19', 'L-19'), ('L-20', 'L-20'), ('L-21', 'L-21'), ('L-22', 'L-22'), ('L-23', 'L-23'), ('L-24', 'L-24'), ('L-25', 'L-25'), ('L-26', 'L-26'), ('L-27', 'L-27'), ('L-28', 'L-28'), ('L-29', 'L-29'), ('L-30', 'L-30'), ('L-31', 'L-31')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='progress',
            field=models.CharField(choices=[('None', '------'), ('in-progress', 'in-progress'), ('approved', 'approved'), ('dismissed', 'dismissed')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='year',
            field=models.CharField(choices=[('N', '------'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('N', '------'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=None, max_length=1, null=True),
        ),
    ]
