# Generated by Django 3.0.4 on 2020-04-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20200420_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorium',
            name='date',
            field=models.DateField(default=None, help_text='Use %YYYY-%MM-%DD format.', null=True),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='reason_for_disapproval',
            field=models.TextField(default=None, help_text='Required, if you are going to disapprove the application', null=True),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='time_from',
            field=models.TimeField(default=None, help_text='In 24 hour notation.', null=True),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='time_to',
            field=models.TimeField(default=None, help_text='In 24 hour notation.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_of_event_from',
            field=models.DateField(default=None, help_text='Use %YYYY-%MM-%DD format.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_of_event_to',
            field=models.DateField(default=None, help_text='Use %YYYY-%MM-%DD format.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_of_event_from',
            field=models.TimeField(default=None, help_text='In 24 hour notation.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_of_event_to',
            field=models.TimeField(default=None, help_text='In 24 hour notation.', null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='date_from',
            field=models.DateField(default=None, help_text='Use %YYYY-%MM-%DD format.', null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='date_to',
            field=models.DateField(default=None, help_text='Use %YYYY-%MM-%DD format.', null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='time_from',
            field=models.TimeField(default=None, help_text='In 24 hour notation.', null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='time_to',
            field=models.TimeField(default=None, help_text='In 24 hour notation.', null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='date_from',
            field=models.DateField(default=None, help_text='Use %YYYY-%MM-%DD format.', null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='date_to',
            field=models.DateField(default=None, help_text='Use %YYYY-%MM-%DD format.', null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='time_from',
            field=models.TimeField(default=None, help_text='In 24 hour notation.', null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='time_to',
            field=models.TimeField(default=None, help_text='In 24 hour notation.', null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='date_of_event_from',
            field=models.DateField(default=None, help_text='Use %YYYY-%MM-%DD format.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='date_of_event_to',
            field=models.DateField(default=None, help_text='Use %YYYY-%MM-%DD format.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='dates_for_which_team_will_be_away_from',
            field=models.DateField(default=None, help_text='Use %YYYY-%MM-%DD format.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='dates_for_which_team_will_be_away_to',
            field=models.DateField(default=None, help_text='Use %YYYY-%MM-%DD format.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='DOB',
            field=models.DateField(default=None, help_text='Use %YYYY-%MM-%DD format.', null=True),
        ),
    ]
