# Generated by Django 3.0.3 on 2020-04-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_auto_20200421_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorium',
            name='datetime',
            field=models.DateTimeField(default=None, help_text='Use %YYYY-%MM-%DD format.', null=True),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='progress',
            field=models.CharField(blank=True, choices=[('None', '------'), ('in-progress', 'in-progress'), ('approved', 'approved'), ('dismissed', 'dismissed')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='progress',
            field=models.CharField(blank=True, choices=[('None', '------'), ('in-progress', 'in-progress'), ('approved', 'approved'), ('dismissed', 'dismissed')], default='in-progress', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lecturehalls',
            name='progress',
            field=models.CharField(blank=True, choices=[('None', '------'), ('in-progress', 'in-progress'), ('approved', 'approved'), ('dismissed', 'dismissed')], default=None, max_length=20, null=True),
        ),
    ]
