# Generated by Django 3.0.3 on 2020-04-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_auto_20200421_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditorium',
            name='datetime',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/statue.jpg', null=True, upload_to='profile_pic/'),
        ),
    ]
