# Generated by Django 3.0.3 on 2020-04-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_auto_20200426_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dream',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobbie1',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobbie2',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobbie3',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobbie4',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('S', 'Single'), ('T', 'Taken'), ('C', 'complicated')], default=None, max_length=1, null=True),
        ),
    ]
