# Generated by Django 3.0.3 on 2020-04-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_auto_20200427_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='intrested_in',
            field=models.CharField(choices=[('N', '------'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thing1',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thing2',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thing3',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('N', '------'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('Single', 'Single'), ('Taken', 'Taken'), ('Complicated', 'Complicated')], default=None, max_length=15, null=True),
        ),
    ]
