# Generated by Django 3.0.3 on 2020-04-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_auto_20200427_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dream',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hobbie1',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hobbie2',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hobbie3',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hobbie4',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='thing1',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='thing2',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='thing3',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
